# config for stylua, ref: https://github.com/JohnnyMorganz/StyLua
syntax = "Lua51"
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses= "NoSingleTable"
